version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: node-html-parser
    versions:
    - 2.1.0
    - 2.2.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
    - 3.1.4
    - 3.1.5
    - 3.1.6
